#!/usr/bin/env bash
# Install the Codex failed-turn watcher as a systemd user service.
#
# Codex sends nothing when a turn dies on a usage limit, a rate limit or a
# safeguard refusal, so the watcher polls its history database instead. This
# script writes the unit with absolute paths filled in, starts it, and enables
# lingering so it keeps running while you are logged out.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
SERVICE_NAME="coding-agent-notifier-codex-watch"
UNIT_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/systemd/user"
UNIT_PATH="$UNIT_DIR/$SERVICE_NAME.service"

INTERVAL=30
INCLUDE_INTERRUPTED=0
ENABLE_LINGER=1
DRY_RUN=0
UNINSTALL=0

usage() {
  cat <<EOF
Usage: $(basename "$0") [options]

  --interval SECONDS      Polling interval (default: $INTERVAL)
  --include-interrupted   Also report turns you interrupted yourself
  --no-linger             Skip 'loginctl enable-linger' (service then stops at logout)
  --dry-run               Print the unit file instead of installing it
  --uninstall             Stop, disable and remove the service
  -h, --help              Show this help
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --interval) INTERVAL="${2:?--interval needs a value}"; shift 2 ;;
    --include-interrupted) INCLUDE_INTERRUPTED=1; shift ;;
    --no-linger) ENABLE_LINGER=0; shift ;;
    --dry-run) DRY_RUN=1; shift ;;
    --uninstall) UNINSTALL=1; shift ;;
    -h|--help) usage; exit 0 ;;
    *) echo "Unknown option: $1" >&2; usage >&2; exit 2 ;;
  esac
done

require_systemd() {
  if ! command -v systemctl > /dev/null 2>&1; then
    echo "systemctl not found. Run the watcher from a cron job instead:" >&2
    echo "  * * * * * $REPO_ROOT/scripts/notifier/codex_watch.py --once" >&2
    exit 1
  fi
  if ! systemctl --user show-environment > /dev/null 2>&1; then
    echo "No systemd user instance is available for this session." >&2
    exit 1
  fi
}

if [[ "$UNINSTALL" == "1" ]]; then
  require_systemd
  systemctl --user disable --now "$SERVICE_NAME" 2>/dev/null || true
  rm -f "$UNIT_PATH"
  systemctl --user daemon-reload
  echo "Removed $UNIT_PATH"
  echo "Lingering was left enabled; 'loginctl disable-linger \"$USER\"' turns it off."
  exit 0
fi

# The service runs outside your shell, so resolve an interpreter that has the
# package installed rather than relying on PATH.
resolve_python() {
  if [[ -n "${NOTIFIER_PYTHON:-}" ]]; then
    echo "${NOTIFIER_PYTHON}"
    return 0
  fi
  local candidate
  for candidate in "$REPO_ROOT/.venv/bin/python" "$REPO_ROOT/venv/bin/python"; do
    [[ -x "$candidate" ]] && { echo "$candidate"; return 0; }
  done
  command -v python3 || command -v python
}

PYTHON_BIN="$(resolve_python || true)"
if [[ -z "$PYTHON_BIN" ]]; then
  echo "No Python interpreter found. Create one with: uv venv && uv pip install -e '.[dev]'" >&2
  exit 1
fi

if ! "$PYTHON_BIN" -c "import coding_agent_notifier" > /dev/null 2>&1; then
  if ! PYTHONPATH="$REPO_ROOT/src" "$PYTHON_BIN" -c "import requests" > /dev/null 2>&1; then
    echo "$PYTHON_BIN cannot import the notifier or requests." >&2
    echo "Install it first: uv venv && uv pip install -e '.[dev]'" >&2
    exit 1
  fi
fi

ENV_ARGS=""
if [[ -f "$REPO_ROOT/.env" ]]; then
  ENV_ARGS=" \\
  --env-file $REPO_ROOT/.env"
elif [[ -z "${SLACK_BOT_TOKEN:-}${LARK_WEBHOOK_URL:-}${FEISHU_WEBHOOK_URL:-}" ]]; then
  echo "Warning: no $REPO_ROOT/.env and no credentials in the environment." >&2
  echo "         The service will start but log that it has nothing to notify with." >&2
fi

INTERRUPTED_ARG=""
[[ "$INCLUDE_INTERRUPTED" == "1" ]] && INTERRUPTED_ARG=" \\
  --include-interrupted"

UNIT_CONTENT="# Generated by scripts/install_codex_watch.sh -- re-run it to change the options.
# Logs: journalctl --user -u $SERVICE_NAME -f

[Unit]
Description=Coding Agent Notifier - Codex failed-turn watcher
After=default.target

[Service]
Type=simple
WorkingDirectory=$REPO_ROOT
ExecStart=$PYTHON_BIN \\
  $REPO_ROOT/scripts/notifier/codex_watch.py$ENV_ARGS \\
  --interval $INTERVAL$INTERRUPTED_ARG
Restart=always
RestartSec=10

[Install]
WantedBy=default.target
"

if [[ "$DRY_RUN" == "1" ]]; then
  printf '%s' "$UNIT_CONTENT"
  exit 0
fi

require_systemd
mkdir -p "$UNIT_DIR"
printf '%s' "$UNIT_CONTENT" > "$UNIT_PATH"
systemctl --user daemon-reload
systemctl --user enable --now "$SERVICE_NAME"

if [[ "$ENABLE_LINGER" == "1" ]]; then
  if loginctl enable-linger "$USER" 2>/dev/null; then
    echo "Lingering enabled; the watcher keeps running while you are logged out."
  else
    echo "Could not enable lingering (try: sudo loginctl enable-linger \"$USER\")." >&2
    echo "The watcher still runs while you are logged in." >&2
  fi
fi

echo "Installed $UNIT_PATH"
systemctl --user --no-pager --lines=0 status "$SERVICE_NAME" | head -3 || true
echo
echo "Follow it with: journalctl --user -u $SERVICE_NAME -f"
